// stores.js — the 58 retailers and their sale-page URLs.
// Keep this in sync with the `STORES` array in public/index.html.
export const STORES = [
  { name: "Macy's",                 category: 'Department',   url: 'https://www.macys.com/shop/sale?id=3536' },
  { name: 'JCPenney',               category: 'Department',   url: 'https://www.jcpenney.com/g/shops/shop-all-products?s1_deals_and_promotions=SALE&id=cat1007450013&cm_re=ZB-_-GALLERY-SHOP-ALL-PRODUCTS-_-VN-_-CLEARANCE-_-SHOP-ALL_6' },
  { name: 'Belk',                   category: 'Department',   url: 'https://www.belk.com/search/?pmid=BelkClearancePricing&isclearancelanding=true' },
  { name: 'Nordstrom',              category: 'Department',   url: 'https://www.nordstrom.com/browse/sale' },
  { name: "Kohl's",                 category: 'Department',   url: 'https://www.kohls.com/catalog/sale.jsp?CN=Promotions:Clearance+Promotions:Sale&BL=y&cc=sale-HZ1-saleclearance' },
  { name: "Dillard's",              category: 'Department',   url: 'https://www.dillards.com/c/sale-clearance' },
  { name: 'Gap',                    category: 'Apparel',      url: 'https://www.gap.com' },
  { name: 'Old Navy',               category: 'Apparel',      url: 'https://oldnavy.gap.com/browse/todays-deals/shop-all?cid=3039764&mlink=5151,topNav,visnav&nav=meganav%3AToday’s%20Deals!%3A%3A' },
  { name: 'American Eagle',         category: 'Apparel',      url: 'https://www.ae.com/us/en/?redirectedFrom=plp' },
  { name: 'Hollister',              category: 'Apparel',      url: 'https://www.hollisterco.com/shop/us' },
  { name: 'Abercrombie & Fitch',    category: 'Apparel',      url: 'https://www.abercrombie.com/shop/us?catalogId=10901&storeId=10051&langId=-1&DM_PersistentCookieCreated=true&categoryId=68948' },
  { name: 'Aéropostale',            category: 'Apparel',      url: 'https://www.aeropostale.com' },
  { name: 'Free People',            category: 'Apparel',      url: 'https://www.freepeople.com/sale-all/' },
  { name: 'H&M',                    category: 'Apparel',      url: 'https://www2.hm.com/en_us/index.html' },
  { name: 'Uniqlo',                 category: 'Apparel',      url: 'https://www.uniqlo.com/us/en/' },
  { name: 'Express',                category: 'Apparel',      url: 'https://www.express.com/exp/clothing-sales?ICID=N_HEADER_SALE' },
  { name: 'Buckle',                 category: 'Apparel',      url: 'https://www.buckle.com' },
  { name: 'PacSun',                 category: 'Apparel',      url: 'https://www.pacsun.com/sale/' },
  { name: 'Urban Outfitters',       category: 'Apparel',      url: 'https://www.urbanoutfitters.com/?ref=logo' },
  { name: 'Anthropologie',          category: 'Apparel',      url: 'https://www.anthropologie.com/?ref=logo' },
  { name: 'J.Crew',                 category: 'Apparel',      url: 'https://www.jcrew.com' },
  { name: 'Banana Republic',        category: 'Apparel',      url: 'https://bananarepublic.gap.com' },
  { name: 'Foot Locker',            category: 'Athletic',     url: 'https://www.footlocker.com' },
  { name: 'Finish Line',            category: 'Athletic',     url: 'https://www.finishline.com' },
  { name: 'Champs Sports',          category: 'Athletic',     url: 'https://www.champssports.com' },
  { name: 'Nike',                   category: 'Athletic',     url: 'https://www.nike.com' },
  { name: 'Adidas',                 category: 'Athletic',     url: 'https://www.adidas.com/us' },
  { name: 'Lululemon',              category: 'Athletic',     url: 'https://shop.lululemon.com' },
  { name: 'Under Armour',           category: 'Athletic',     url: 'https://www.underarmour.com/en-us/' },
  { name: "Dick's Sporting Goods",  category: 'Athletic',     url: 'https://www.dickssportinggoods.com' },
  { name: 'Sephora',                category: 'Beauty',       url: 'https://www.sephora.com' },
  { name: 'Ulta Beauty',            category: 'Beauty',       url: 'https://www.ulta.com' },
  { name: 'Bath & Body Works',      category: 'Beauty',       url: 'https://www.bathandbodyworks.com' },
  { name: 'MAC Cosmetics',          category: 'Beauty',       url: 'https://www.maccosmetics.com/sale' },
  { name: 'The Body Shop',          category: 'Beauty',       url: 'https://us.thebodyshop.com' },
  { name: 'Apple',                  category: 'Tech',         url: 'https://www.apple.com' },
  { name: 'Best Buy',               category: 'Tech',         url: 'https://www.bestbuy.com' },
  { name: 'GameStop',               category: 'Tech',         url: 'https://www.gamestop.com' },
  { name: 'Microsoft Store',        category: 'Tech',         url: 'https://www.microsoft.com/en-us/store/b/sale' },
  { name: 'Pandora',                category: 'Jewelry',      url: 'https://us.pandora.net/en/jewelry/sale/?mptGroup=control&site=us&search_engine=bloomreach' },
  { name: 'Kay Jewelers',           category: 'Jewelry',      url: 'https://www.kay.com' },
  { name: 'Zales',                  category: 'Jewelry',      url: 'https://www.zales.com' },
  { name: "Claire's",               category: 'Accessories',  url: 'https://www.claires.com' },
  { name: 'Sunglass Hut',           category: 'Accessories',  url: 'https://www.sunglasshut.com/us/sale' },
  { name: 'Pottery Barn',           category: 'Home',         url: 'https://www.potterybarn.com' },
  { name: 'Williams Sonoma',        category: 'Home',         url: 'https://www.williams-sonoma.com/shop/sale-special-offer/' },
  { name: 'Crate & Barrel',         category: 'Home',         url: 'https://www.crateandbarrel.com/sale/' },
  { name: 'Yankee Candle',          category: 'Home',         url: 'https://www.yankeecandle.com/yankee-candle/sale/special-offers/' },
  { name: 'DSW',                    category: 'Shoes',        url: 'https://www.dsw.com/content/coupons-and-promo-codes?cm_xm=nav-dswdealsnav' },
  { name: 'Famous Footwear',        category: 'Shoes',        url: 'https://www.famousfootwear.com/browse/sale?icid=sdd_vwall#sortCriteria=relevance' },
  { name: 'Journeys',               category: 'Shoes',        url: 'https://www.journeys.com' },
  { name: 'Vans',                   category: 'Shoes',        url: 'https://www.vans.com/en-us/c/sale-5410' },
  { name: 'Crocs',                  category: 'Shoes',        url: 'https://www.crocs.com/c/sale' },
  { name: 'LEGO',                   category: 'Specialty',    url: 'https://www.lego.com/en-us/page/lego-offers-promotions' },
  { name: 'Disney Store',           category: 'Specialty',    url: 'https://www.disneystore.com/sale-content/' },
  { name: 'Hot Topic',              category: 'Specialty',    url: 'https://www.hottopic.com/sale/shop-all-clearance/' },
  { name: 'Build-A-Bear Workshop',  category: 'Specialty',    url: 'https://www.buildabear.com/' },
  { name: 'Barnes & Noble',         category: 'Books & Fun',  url: 'https://www.barnesandnoble.com/pages/bestsellers' },
];
